<?php 

header("Content-type: image/jpeg");
$data = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABsbGxscGx4hIR4qLSgtKj04MzM4PV1CR0JHQl2NWGdYWGdYjX2Xe3N7l33gsJycsOD/2c7Z//////////////8BGxsbGxwbHiEhHiotKC0qPTgzMzg9XUJHQkdCXY1YZ1hYZ1iNfZd7c3uXfeCwnJyw4P/Zztn////////////////CABEIAD4AIwMBIgACEQEDEQH/xAAuAAACAwEAAAAAAAAAAAAAAAAAAwECBAUBAAMBAAAAAAAAAAAAAAAAAAABAwL/2gAMAwEAAhADEAAAAO6u1LRqtlGLJA2Vzk9totbTjMBybvRGwndnaSJNZ387o48Ue2LJwSB//8QAJhAAAgEDAgYCAwAAAAAAAAAAAAECAwQREBITISIxQUIUYTJRUv/aAAgBAQABPwBjGNaMYx6MaGhowSvaCx1Hy6D9yVzSj3mVLujDHUK8oP2JrMvs2sab7m2GXuNtH9mLdwW5S3eWVKlGlKCjux5FO2f9FedHlw02yXfknpc/mUU+HHJhGNLmEelkOUUvrTJ//8QAGREAAgMBAAAAAAAAAAAAAAAAAAECEBIR/9oACAECAQE/AFakaNXxCv8A/8QAGBEAAwEBAAAAAAAAAAAAAAAAABARASH/2gAIAQMBAT8AcIRcWv8A/9k=";
echo base64_decode($data);


echo '<img src="data:image/jpeg;base64,' . $data . '" />';